import { useEffect, useRef, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { trackEvent } from "@/lib/analytics";

export function MuutosturvaFormModal({open,onOpenChange,initialCourse=""}: {open:boolean;onOpenChange:(open:boolean)=>void;initialCourse?:string}) {
 const [step,setStep]=useState(1);
 const [values,setValues]=useState<Record<string,string>>({});
 const [errors,setErrors]=useState<Record<string,string>>({});
 const [busy,setBusy]=useState(false);
 const [sent,setSent]=useState(false);
 const [failure,setFailure]=useState("");
 const opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(open){opener.current=document.activeElement as HTMLElement;trackEvent("assessment_opened");}},[open]);
 useEffect(()=>{if(initialCourse){const [course,detail=""]=initialCourse.split(" – ");setValues(v=>({...v,course,level:course.includes("koordinaattori")?"Tekoälykoordinaattori":course.includes("päällikkö")?"Tekoälypäällikkö":"Tekoälyjohtaja",industry:detail.startsWith("aloitus")?v.industry||"":detail,start:detail.startsWith("aloitus")?detail.replace("aloitus ",""):""}));}},[initialCourse]);
 const change=(key:string,value:string)=>{setValues(v=>({...v,[key]:value}));};
 const close=(next:boolean)=>{if(busy)return;if(!next){setValues(v=>({course:v.course||"",industry:v.industry||"",level:v.level||"",start:""}));setStep(1);setSent(false);setErrors({});setFailure("");}onOpenChange(next);};
 const labels:Record<string,string>={dismissed:"Onko sinut irtisanottu tuotannollisista tai taloudellisista syistä?",name:"Nimi",email:"Sähköposti",phone:"Puhelinnumero",age:"Oletko vähintään 55-vuotias?",date:"Milloin työsuhteesi päättyi tai päättyy?",goal:"Mitä tavoittelet seuraavaksi?",course:"Valittu koulutus",industry:"Kiinnostava koulutusala",level:"Kiinnostava pätevyystaso",start:"Toivottu aloitusajankohta / aloitusryhmä",extra:"Vapaa lisätieto"};
 const field=(key:string,options?:string[],type="text",required=false)=><div className="space-y-1" key={key}><Label htmlFor={`assessment-${key}`}>{labels[key]}{required?" *":" (vapaaehtoinen)"}</Label>{options?<select id={`assessment-${key}`} className="w-full min-h-11 rounded-md border border-input bg-background px-3 text-sm" value={values[key]||""} onChange={e=>change(key,e.target.value)} aria-required={required} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined}><option value="">Valitse</option>{options.map(o=><option key={o}>{o}</option>)}</select>:<Input id={`assessment-${key}`} className="min-h-11" type={type} maxLength={key==="extra"?700:150} value={values[key]||""} onChange={e=>change(key,e.target.value)} aria-required={required} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined} />}{errors[key]&&<p id={`${key}-error`} className="text-sm text-destructive">{errors[key]}</p>}</div>;
 const next=()=>{const e:Record<string,string>={};for(const k of ["dismissed","name","email"]){if(!values[k]?.trim())e[k]="Täytä tämä pakollinen tieto.";}if(values.name?.trim().length===1)e.name="Kirjoita koko nimesi.";if(values.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email))e.email="Kirjoita kelvollinen sähköpostiosoite.";setErrors(e);if(Object.keys(e).length){document.getElementById(`assessment-${Object.keys(e)[0]}`)?.focus();return;}setStep(2);trackEvent("assessment_step1_completed");};
 const submit=async()=>{setBusy(true);setFailure("");try{const message=Object.entries(labels).filter(([k])=>!["name","email","phone"].includes(k)).map(([k,l])=>`${l}: ${k==="date"&&values.unknown?"En tiedä":values[k]||"–"}`).join("\n");const {data,error}=await supabase.functions.invoke("send-booking-request",{body:{name:values.name,email:values.email,phone:values.phone,message,source:"muutosturva-kartoitus",meetingFormat:"Muutosturvakartoitus"}});if(error||!data?.ok)throw new Error();setSent(true);trackEvent("assessment_submitted");}catch{setFailure("Lähetys ei onnistunut. Tietosi säilyvät tässä lomakkeessa – yritä hetken kuluttua uudelleen tai ota yhteyttä puhelimitse tai sähköpostilla.");trackEvent("assessment_failed");}finally{setBusy(false);}};
 return <Dialog open={open} onOpenChange={close}><DialogContent className="z-[110] max-w-2xl h-auto max-h-[85svh] w-[calc(100%-1rem)] top-4 translate-y-0 sm:top-1/2 sm:-translate-y-1/2 flex flex-col overflow-hidden p-4 sm:p-6 [&>button]:min-h-11 [&>button]:min-w-11" onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onInteractOutside={e=>e.preventDefault()} onCloseAutoFocus={e=>{e.preventDefault();opener.current?.focus();}}><DialogHeader className="shrink-0 pr-10 max-h-[30dvh] overflow-y-auto"><DialogTitle>{sent?"Kiitos – kartoituksesi on vastaanotettu.":"Maksuton muutosturvakartoitus"}</DialogTitle><DialogDescription>{sent?"Olemme sinuun yhteydessä ja käymme läpi sopivan koulutuksen, mahdollisen aloituksen sekä muutosturvan etenemistavan. Älä ilmoittaudu maksulliseen koulutukseen ennen kuin rahoitus ja eteneminen on varmistettu.":"Tämä ei ole sitova ilmoittautuminen. Kartoituksen perusteella olemme sinuun yhteydessä ja autamme selvittämään sopivan koulutuksen, rahoituksen ja etenemistavan."}</DialogDescription></DialogHeader>
 <div className="overflow-y-auto min-h-0 space-y-4 py-2" key={sent?"sent":step}>
 {sent?<p>{values.course&&`Valittu koulutus: ${values.course}`}</p>:<><p className="font-semibold text-primary" aria-live="polite">Vaihe {step}/2 – {step===1?"Tilanteesi":"Koulutustoiveet"}</p>{step===1?<><p className="text-sm text-muted-foreground">Tähdellä (*) merkityt tiedot ovat pakollisia.</p>{field("age",["Kyllä","Ei"],"text",true)}{field("dismissed",["Kyllä","Ei","En ole varma"],"text",true)}{!values.unknown&&field("date",undefined,"date",true)}<label className="flex items-center gap-2 min-h-11"><input type="checkbox" checked={!!values.unknown} onChange={e=>change("unknown",e.target.checked?"yes":"")}/>En tiedä työsuhteen päättymispäivää</label>{field("goal",["Työllistyminen","Alanvaihto","Osaamisen päivittäminen","En vielä tiedä"],"text",true)}{field("name",undefined,"text",true)}{field("email",undefined,"email",true)}{field("phone",undefined,"tel")}</>:<>{field("course")}{field("previous")}{field("industry")}{field("level",["Tekoälykoordinaattori","Tekoälypäällikkö","Tekoälyjohtaja","En vielä tiedä","Muu"])}{field("ai",["En ole käyttänyt tekoälyä","Olen kokeillut","Käytän säännöllisesti","Hyödynnän monipuolisesti","Muu"])}{field("start")}{field("extra")}</>}{failure&&<p role="alert" className="text-destructive text-sm">{failure}</p>}</>}
 <div className="flex flex-wrap gap-3 text-sm"><a className="underline min-h-11 inline-flex items-center" href="tel:+358401906912" onClick={()=>trackEvent("assessment_phone_clicked")}>040 190 6912</a><a className="underline min-h-11 inline-flex items-center" href="mailto:heikki.kallunki@keuda.fi" onClick={()=>trackEvent("assessment_email_clicked")}>heikki.kallunki@keuda.fi</a></div></div>
 <div className="flex gap-3 shrink-0 border-t pt-3">{sent?<Button onClick={()=>close(false)}>Sulje</Button>:step===1?<Button variant="cta" className="min-h-11" onClick={next}>Jatka</Button>:<><Button variant="outline" disabled={busy} onClick={()=>setStep(1)}>Takaisin</Button><Button variant="cta" className="min-h-11" disabled={busy} onClick={submit}>{busy?"Lähetetään…":"Lähetä kartoitus"}</Button></>}</div></DialogContent></Dialog>;
}
